import type { UserProfile } from '@/types'

export const DEMO_USERS: Record<string, UserProfile> = {
  'student@interniq.io': {
    id: 'usr_student_001',
    full_name: 'Arjun Mehta',
    email: 'student@interniq.io',
    role: 'student',
    avatar_url: null,
    phone: '+91 98765 43210',
    department_id: 'dept_001',
    batch_id: 'batch_001',
    company_id: 'comp_001',
    employee_id: null,
    enrollment_number: 'CS2024001',
    year_of_study: 3,
    designation: null,
    institution_name: 'National Institute of Technology',
    industry_sector: null,
    status: 'active',
    created_at: '2024-08-01T00:00:00Z',
  },
  'faculty@interniq.io': {
    id: 'usr_faculty_001',
    full_name: 'Dr. Priya Sharma',
    email: 'faculty@interniq.io',
    role: 'faculty_mentor',
    avatar_url: null,
    phone: '+91 98765 11111',
    department_id: 'dept_001',
    batch_id: null,
    company_id: null,
    employee_id: 'FAC2024001',
    enrollment_number: null,
    year_of_study: null,
    designation: 'Associate Professor',
    institution_name: 'National Institute of Technology',
    industry_sector: null,
    status: 'active',
    created_at: '2024-01-15T00:00:00Z',
  },
  'industry@interniq.io': {
    id: 'usr_industry_001',
    full_name: 'Rahul Kapoor',
    email: 'industry@interniq.io',
    role: 'industry_mentor',
    avatar_url: null,
    phone: '+91 98765 22222',
    department_id: null,
    batch_id: null,
    company_id: 'comp_001',
    employee_id: null,
    enrollment_number: null,
    year_of_study: null,
    designation: 'Engineering Manager',
    institution_name: null,
    industry_sector: 'Technology',
    status: 'active',
    created_at: '2024-02-10T00:00:00Z',
  },
  'admin@interniq.io': {
    id: 'usr_admin_001',
    full_name: 'Kavita Desai',
    email: 'admin@interniq.io',
    role: 'admin',
    avatar_url: null,
    phone: '+91 98765 33333',
    department_id: null,
    batch_id: null,
    company_id: null,
    employee_id: 'ADM001',
    enrollment_number: null,
    year_of_study: null,
    designation: 'Placement Officer',
    institution_name: 'National Institute of Technology',
    industry_sector: null,
    status: 'active',
    created_at: '2023-06-01T00:00:00Z',
  },
}
